### ISSUE TITLE
update cucumber-gherkin dependency

### ISSUE THREAD

**Issue by waynemd** [enkessler/cuke_modeler#10]
I raise an issue with parallel_tests gem here (https://github.com/grosser/parallel_tests/issues/816), but it might be related to the cucumber-gherkin dependency version in cuke_modeler.

Bundler could not find compatible versions for gem "cucumber-gherkin":

```
  In Gemfile:
    cucumber (= 6.0.0) was resolved to 6.0.0, which depends on
      cucumber-gherkin (>= 18.1.0, ~> 18.1)

    cuke_modeler (~> 3.0) was resolved to 3.7.0, which depends on
      cucumber-gherkin (< 18.0)
```

**Comment by waynemd** [comment]
Support Gherkin 18.x will resolve the issue.

**Comment by enkessler** [comment]
I didn't see this issue until now. Sorry about that. Coincidentally, adding 18.x support was on my list of things to do anyway.
