### ISSUE TITLE
Unnecessary 2.2.0 cucumber pinned version?

### ISSUE THREAD

**Issue by Apteryks** [enkessler/cuke_modeler#14]
Hello,

I was puzzled about the `'cucumber',  2.2.0'` specification in the Gemfile, so I've patched it to be `>= 2.2.0` and tried running the `default` rake target, and to my surprises it runs fine:

```
starting phase `check'
Clearing report directory...
Running tests...
Running RSpec tests...
Testing with dialect 'en-Scouse'...
Run options: exclude {:wip=>true}
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 2.26 seconds (files took 1.02 seconds to load)
1343 examples, 0 failures

Coverage report generated for rspec_tests to /tmp/guix-build-ruby-cuke-modeler-3.19.0.drv-0/source/reports/coverage. 1036 / 1100 LOC (94.18%) covered.
Lcov style coverage report generated for rspec_tests to /tmp/guix-build-ruby-cuke-modeler-3.19.0.drv-0/source/reports/coverage/lcov/lcov.info
All RSpec tests passing.
Running Cucumber tests...
`/homeless-shelter` is not a directory.
Bundler will use `/tmp/guix-build-ruby-cuke-modeler-3.19.0.drv-0/bundler20230316-33-1d1yhwp33' as your home directory temporarily.
/gnu/store/frhaqvx1i79a1y4w8xfxr2s3c0539lzb-ruby-mime-types-3.1/lib/ruby/vendor_ruby/gems/mime-types-3.1/lib/mime/types/logger.rb:28: warning: `_1' is reserved for numbered parameter; consider another name
/gnu/store/frhaqvx1i79a1y4w8xfxr2s3c0539lzb-ruby-mime-types-3.1/lib/ruby/vendor_ruby/gems/mime-types-3.1/lib/mime/types/logger.rb:28: warning: `_2' is reserved for numbered parameter; consider another name
/gnu/store/frhaqvx1i79a1y4w8xfxr2s3c0539lzb-ruby-mime-types-3.1/lib/ruby/vendor_ruby/gems/mime-types-3.1/lib/mime/types/logger.rb:28: warning: `_3' is reserved for numbered parameter; consider another name
Using the default, html and wip_filter profiles...
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

102 scenarios (102 passed)
539 steps (539 passed)
0m1.257s
Formatter SimpleCov::Formatter::HTMLFormatter failed with Errno::EACCES: Permission denied @ rb_sysopen - /tmp/guix-build-ruby-cuke-modeler-3.19.0.drv-0/source/reports/coverage/assets/0.12.3/DataTables-1.10.20/images/sort_asc.png (/gnu/store/j4z07lyi1ykk8bc68h1p4bpj1il9dn3f-ruby-2.7.4/lib/ruby/2.7.0/fileutils.rb:1415:in `initialize')
Lcov style coverage report generated for cucumber_tests, rspec_tests to /tmp/guix-build-ruby-cuke-modeler-3.19.0.drv-0/source/reports/coverage/lcov/lcov.info
All Cucumber tests passing.
All tests passing!
phase `check' succeeded after 7.6 seconds
```
These are the direct dependency versions in my environment:
```
ruby-childprocess@3.0.0 ruby-cucumber-gherkin@26.0.3 ruby-cucumber@8.0.0
+ ruby-rainbow@3.0.0 ruby-rspec@3.12.0 ruby-simplecov-lcov@0.8.0 ruby-simplecov@0.22.0
```

Perhaps it could be updated?

Thanks!

**Comment by enkessler** [comment]
> These are the direct dependency versions in my environment:
> 
> ```
> ruby-childprocess@3.0.0 ruby-cucumber-gherkin@26.0.3 ruby-cucumber@8.0.0
> + ruby-rainbow@3.0.0 ruby-rspec@3.12.0 ruby-simplecov-lcov@0.8.0 ruby-simplecov@0.22.0
> ```

I'm not sure how you're running the tests, in that case, because those dependencies are not compatible with each other. If you drop `gem 'cucumber-gherkin', "26.0.3"` and `gem 'cucumber', "8.0.0"` into your gemfile, Bundler won't even get past installation because `cucumber` does not currently support any version of `cucumber-gherkin` past `23.x`.

> I was puzzled about the `'cucumber',  2.2.0'` specification in the Gemfile, so I've patched it to be `>= 2.2.0` and tried running the  `default` rake target, and to my surprises it runs fine

The usage of `2.2.0` is conditional. It depends on which version of `cucumber-gherkin` you want to use when running the tests.
https://github.com/enkessler/cuke_modeler/blob/e3048422da99bcd7f926d7be1c876b03c5001fa0/Gemfile#L7
Will CukeModeler run with any version of Cucumber? Yes. Will Cucumber run with any version of Gherkin? No. Cucumber `2.2.0` is special because it uses a version of Gherkin that doesn't use the `Gherkin` namespace, thus allowing it to not conflict with the namespace of whatever version of `cucumber-gherkin` is being tested.

**Comment by Apteryks** [comment]
Hello!  Thanks for the clarifications.  I think I'm able to use cucumber 8 with gherkin 26 because I must have tweaked the gemspec files a bit to allow that, and generally do not use Bundler (as the Gemfiles often include extraneous dependencies that'd need to be patched out and the environment is already managed by Guix).  I try running the test suites where practicable, so I have at least some confidence that the components fit together.  I wonder why cucumber can't use the latest gherkin.

**Comment by enkessler** [comment]
> I wonder why cucumber can't use the latest gherkin.

It's less an issue of "can't" and more an issue of "won't".

https://github.com/cucumber/cucumber-ruby/pull/1688

Keeping the `cucumber-gherkin` dependency up to date may be so trivial as to be able to be done by a bot but that does not mean that the maintainers are inclined to make a new release when those updates happen. Additionally, they have a habit of skipping dependency versions. So, rather than the next release going from being compatible with Gherkin 23.x to being compatible with 23.x-26.x, they may decide to just lock it to only 26.x, leaving anyone who needs 24.x or 25.x out in the cold.

**Comment by Apteryks** [comment]
OK.  I see the referenced PR has been merged so cucumber 8 can use gherking 26 as long as it's < 26.0.3, and as of 4 days ago they've bumped it again to  < 26.1.1.  They could probably use the compatible operator instead, something like ~>26.0, which seems to me like would be less tedious and create less friction.  I've asked here if it's something they could consider: https://github.com/cucumber/cucumber-ruby/issues/1701.

**Comment by luke-hill** [comment]
The reason we keep cucumber gherkin so tightly pinned was debated a while back and answered. The long and the short of it is they should be thought of as package private for the inter-dependency to cucumber. People who use gherkin elsewhere can pin their own dependency rules (Such as for spinach).

**Comment by Apteryks** [comment]
@luke-hill Thanks for taking the time answer the question! The problem I'd see with this is when using e.g. spinach and cucumber in the same project; they might disagree on the version of gherkin to use, which would be less likely with a 'compatible' specification, but I guess this was discussed already.

**Comment by enkessler** [comment]
> ... I guess this was discussed already.

@Apteryks There was a rather [lengthy discussion](https://github.com/cucumber/cucumber-ruby/issues/1453) on the topic, yes. With some of the same people involved and the same conclusion reached, even.
