### ISSUE TITLE
QoL: implement #inspect on model objects

### ISSUE THREAD

**Issue by BillyRuffian** [enkessler/cuke_modeler#15]
Hi Eric,

I would like to suggest implementing `#inspect` on the model objects with a terse return value as a quality of life improvement. 

Currently, if I do something stupid and cause an exception to be raised, I'll get the full model rendered through `#to_s` which will swamp the console and obscure the exception message. This hinders experimentation in irb.

**Comment by enkessler** [comment]
Yeah, that should be doable. I'll try to get something out in a week or two.

**Comment by enkessler** [comment]
@BillyRuffian
Implemented and released. Enjoy.
