### ISSUE TITLE
Upgrading from 0.4.1 to 1.0.3 results in undefined method `row_elements`

### ISSUE THREAD

**Issue by saideepakb** [enkessler/cuke_modeler#3]
I recently upgraded from 0.4.1 to 1.4.3 and am getting the following error

```
NoMethodError: undefined method `row_elements' for #
<CukeModeler::Example:0x00000002f75560>
from vendor/bundle/ruby/gems/cuke_slicer-2.0.0/lib/cuke_slicer/helpers/extraction_helpers.rb:33:
in `block (2 levels) in extract_runnable_elements'
```

This seems to happen only when there is a Scenario Outline present in `test_directory` in  

`=> 11: tests = CukeSlicer::Slicer.new.slice(test_directory, filters, :file_line)` (this is something we wrote)

**Comment by enkessler** [comment]
This gem is [semantically versioned](http://semver.org/). As such, upgrading from 0.x to 1.x is likely to introduce breaking changes. In your case, `Example#row_elements` no longer exists. Please use `Example#rows` instead.

**Comment by saideepakb** [comment]
As @cartoloupe has noticed and taken action, I ran into trouble in cuke_slicer and not cuke_modeler. I hope the Gemfile in the cuke_slicer specifies a cuke_modeler version to be able to run Scenario Outlines.

Thanks
